# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_contents', models.TextField()),
                ('related_group', models.TextField()),
                ('admin_dislike', models.BooleanField()),
            ],
        ),
    ]
