# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_group_favor', models.IntegerField()),
                ('curation_folder', models.IntegerField()),
                ('future_possible_group', models.IntegerField()),
                ('past_group_favor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group', models.IntegerField()),
                ('current_user_favor', models.IntegerField()),
                ('curation_folder', models.IntegerField()),
                ('past_user_group', models.IntegerField()),
                ('past_user_favor', models.IntegerField()),
            ],
        ),
    ]
